#!/bin/bash

python3.8 2_new_task.py First message.
python3.8 2_new_task.py Second message..
python3.8 2_new_task.py Third message...
python3.8 2_new_task.py Fourth message....
python3.8 2_new_task.py Fifth message.....
python3.8 2_new_task.py Sixth message......
python3.8 2_new_task.py Seventh message......
python3.8 2_new_task.py Eighth message........
python3.8 2_new_task.py Ninth message.........
python3.8 2_new_task.py Tenth message..........
